
language: android

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - lynx

android:
  components:
    - platform-tools
    - tools

    - build-tools-24.0.2

    - android-25

script:
  - ./gradlew build
  - if [ -f /home/travis/build/billthefarmer/miditest/build/outputs/lint-results-debug.html ]; then lynx -dump /home/travis/build/billthefarmer/miditest/build/outputs/lint-results-debug.html; fi
