
language: android

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - lynx

android:
  components:
    - platform-tools
    - tools

    - build-tools-24.0.2

    - android-25

script:
  - ./gradlew build
